#version 460
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(r32ui, binding = 0) uniform uimage2D InputTexR;
layout(r32ui, binding = 1) uniform uimage2D InputTexG;
layout(r32ui, binding = 2) uniform uimage2D InputTexB;
layout(rgba32f, binding = 3) uniform image2D OutputTex;

const float COLOR_SCALE_INV = 1.0f / 10000.0f;

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    if (pixel_coords.x >= imageSize(OutputTex).x || 
        pixel_coords.y >= imageSize(OutputTex).y) {
        return;
    }
    
    uint r_int = imageLoad(InputTexR, pixel_coords).r;
    uint g_int = imageLoad(InputTexG, pixel_coords).r;
    uint b_int = imageLoad(InputTexB, pixel_coords).r;
    
    vec3 float_color = vec3(r_int, g_int, b_int) * COLOR_SCALE_INV;
    
    imageStore(OutputTex, pixel_coords, vec4(float_color, 1.0f));
}