#version 460 core

layout(binding = 0, rgba32f) uniform readonly image2D CurrentFrame;
layout(binding = 1, rgba32f) uniform readonly image2D PreviousFrame;
layout(binding = 2, rgba32f) uniform writeonly image2D OutputImage;

layout(location = 0) uniform uint FrameCounter;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    
    if (pixel_coords.x >= imageSize(OutputImage).x || 
        pixel_coords.y >= imageSize(OutputImage).y) {
        return;
    }
    
    float blend_factor = 1.0f / float(FrameCounter + 1);
    
    vec4 current_power = imageLoad(CurrentFrame, pixel_coords) * blend_factor;
    vec4 previous_power = imageLoad(PreviousFrame, pixel_coords) * (1.0f - blend_factor);
    vec4 power = current_power + previous_power;
    
    imageStore(OutputImage, pixel_coords, power);
}