#version 460

#extension GL_ARB_shading_language_include : require

#include "shape/shape.glsl"
#include "spectrum/spectrum.glsl"

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 0) writeonly uniform image2D outputTex;
            
// 相机参数 (您可以通过Uniform传递这些值，这里先写死用于测试)
vec3 camera_position = vec3(0.0, 0.0, 5.0); // 相机位置
vec3 camera_target = vec3(0.0, 0.0, 0.0);  // 相机目标点
float camera_fov = radians(60.0);           // 视野角度（弧度）

void main()
{
    uint id = gl_GlobalInvocationID.x;
	if (id >= 1280 * 720) return; // out of bounds

	// convert thread id into screen coordinates
	uint px = id % 1280, py = id / 1280;
	float u = float( px ) / 1280.0f, v = float( py ) / 720.0f;

	// construct primary ray
	const vec3 eye = vec3( 0.5, 0.5, -4 );
	const vec3 view = vec3( 0, 0, 1 );
	const vec3 C = eye + view;
	const vec3 p1 = C + vec3( -1.6f, 1, 0 );
	const vec3 p2 = C + vec3( 1.6f, 1, 0 );
	const vec3 p3 = C + vec3( -1.6f, -1, 0 );
	const vec3 P = p1 + u * (p2 - p1) + v * (p3 - p1);
	const vec3 D = normalize( P - eye );
	const vec3 rD = vec3( 1.0f / D.x, 1.0f / D.y, 1.0f / D.z );
    Ray test_ray;
    test_ray.tmin = 0.001f;
    test_ray.tmax = MaxFloat;
    test_ray.origin = eye;
    test_ray.direction = D;
    
    Hit hit = BVHTraverse(test_ray);

    vec4 color = vec4(hit.distance < MaxFloat ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0), 1.0);
    
    imageStore(outputTex, ivec2(gl_GlobalInvocationID.xy), color);
}